### PR TITLE
Try to reproduce error seen during build_all_repos

### PR DESCRIPTION
**Pull request by jrha**
DO NOT MERGE
This exists purely to trigger tests

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha build all repos ran fine for me on el6 and el7, but not yet on el5

**Comment by jrha** [comment]
I keep seeing these failures on EL6
```
#   Failed test 'Version from package set'
#   at src/test/perl/component-load.t line 96.
#          got: 'v1.2.3'
#     expected: '1.2.3'

#   Failed test 'Version from package set (bar use foo module)'
#   at src/test/perl/component-load.t line 113.
#          got: 'v1.2.3'
#     expected: '1.2.3'
```

**Comment by stdweird** [comment]
can you run
```
perl -e 'use version;print $version::VERSION,"\n";'
```

**Comment by jrha** [comment]
0.77

**Comment by jrha** [comment]
I'll try it on CentOS 6 as well as SL 6.

**Comment by stdweird** [comment]
it should be easy to reproduce this (if this is with build_all_repos, set the environment as dumped at the end of the output)

if you can, add following before the line 96 with the `is()` test

```perl
use version;
diag "version ", $version::VERSION;
my $v1 = $cmp->{VERSION_PACKAGE};
my $v2 = version->new('1.2.3');
diag 'v1 ', " $v1 ", explain $v1;
diag 'v2 ', " $v2 ", explain $v2;
diag "INC ",  explain \@INC, explain \%INC;
```

**Comment by jrha** [comment]
https://gist.github.com/jrha/3857b84c1e8fe2f84807f5a8e861de14

**Comment by stdweird** [comment]
hmmm, centos has differtent location of the `version.pm` module. anyway, i think it's safe to modify the tests to use `v1.2.3` as well, it's what the components use for templating (https://github.com/quattor/maven-tools/blob/master/build-profile/pom.xml#L48)

**Comment by jrha** [comment]
Both my SL 6 and CentOS 6 VMs have the version module in the same place, from RPMs with the same name and version (perl-version-0.77-144.el6.x86_64) and both modules have the same hash.

**Comment by stdweird** [comment]
@jrha oops i check th elocation on a c7 box...
the only other culprit could be `Test::More` as the way `is()` compares instances (stringification or something else). i'd suggest to make a PR to modify the tests. i don't have this on my centos6 images but i don't have too much time to spend on debugging this.

**Comment by jrha** [comment]
Sure, I've run out of time today (have to go to the aiport soon), but I'll look again on Wednesday after the holiday.

**Comment by stdweird** [comment]
Should be fixed by #115 
@jrha i'll leave thgis to you to close?

**Comment by jrha** [comment]
Was indeed resolved by #115, thanks!

**Pull request closed without merging**
