### PR TITLE
Add graph based report of component dependencies

### PR DESCRIPTION
**Pull request by jrha**
Essentially `--list` in graph form.
This also highlights the sorted execution order for all components.

For example:
comps

### CODE REVIEW

**Comment by stdweird** [comment]
so pam, auotfs and resolver are missing a dep on spma :wink:

**Comment by jrha** [comment]
Now with updated tests.
@stdweird  I'll open PRs to fix those components.

**Comment by stdweird** [comment]
@jrha it's probably best to clean those component templates a bit up using the existing maven templates like https://github.com/quattor/configuration-modules-core/blob/master/ncm-accounts/src/main/pan/components/accounts/config.pan#L1

**Review by stdweird — APPROVED** [review]

**Comment by stdweird** [comment]
ugh, i totally forgot #126 is not merged. that will conflict with this PR...

**Comment by jrha** [comment]
:disappointed: if you can deal with the comments on #126 I am happy to rebase this and deal with the conflicts.

**Comment by jrha** [comment]
For reference, this is the same host when switched over to use `spmalight` (which is what sent me down this rabbit-hole in the first place.
comps

**Comment by stdweird** [comment]
i guess the spmalight code was started too late (copying the deps on autofs/resolver/pam)?

**Comment by stdweird** [comment]
@jrha wrt #126, i'll have a look at the tests

**Comment by stdweird** [comment]
#126 is fixed

**Comment by jrha** [comment]
Rebased now that #126 is merged.

**Pull request merged**
